# Generated by Django 4.1 on 2022-08-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
