# Generated by Django 4.1 on 2022-08-17 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_column='dt_created')),
                ('updated', models.DateTimeField(db_column='dt_updated', default=django.utils.timezone.now)),
                ('keyword', models.CharField(db_column='ds_keyword', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'KeyWords',
                'verbose_name_plural': 'KeyWords',
                'db_table': 'tb_keywords',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_column='dt_created')),
                ('updated', models.DateTimeField(db_column='dt_updated', default=django.utils.timezone.now)),
                ('title', models.CharField(db_column='ds_title', max_length=100)),
                ('subtitle', models.CharField(db_column='ds_subtitle', max_length=100)),
                ('type_post', models.IntegerField(db_column='in_type')),
                ('content', models.TextField(db_column='tx_content')),
                ('status', models.IntegerField(db_column='in_status')),
                ('keyword', models.ManyToManyField(db_column='ds_keyword', to='base.keyword')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'tb_post',
            },
        ),
    ]
