# Generated by Django 4.1 on 2022-08-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_keyword_keyword_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='name',
            new_name='keyword_set',
        ),
    ]
