# Generated by Django 4.1 on 2022-08-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_name_keyword_keyword_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='keyword',
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.ManyToManyField(db_column='ds_keywords', to='base.keyword'),
        ),
    ]
