# Generated by Django 4.1 on 2022-08-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_post_keywords_post_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='keyword_set',
            new_name='name',
        ),
    ]
