# Generated by Django 4.1 on 2022-08-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_keyword_set_keyword_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveIntegerField(db_column='in_status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_post',
            field=models.PositiveIntegerField(db_column='in_type'),
        ),
    ]
